/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package turnsform;

import java.util.logging.Level;
import java.util.logging.Logger;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author ART
 */
public class FTurnsInsert extends javax.swing.JFrame {

    /**
     * Creates new form FTurnsInsert
     */
    public FTurnsInsert() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButtonInserir = new javax.swing.JButton();
        jButtonVoltar = new javax.swing.JButton();
        jFTIsbn = new javax.swing.JTextField();
        inputInitTime = new javax.swing.JTextField();
        inputEndTime = new javax.swing.JTextField();
        jCheckBox1 = new javax.swing.JCheckBox();
        weekDayInput = new javax.swing.JTextField();
        labelWeek = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setText("Inserir Turnos");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, -1, -1));

        jLabel2.setText("Data:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, -1, -1));

        jLabel3.setText("Hora Inicio:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, -1, -1));

        jLabel4.setText("Hora Fim:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, -1, -1));

        jButtonInserir.setText("Inserir");
        jButtonInserir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonInserirMouseClicked(evt);
            }
        });
        jButtonInserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInserirActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonInserir, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 360, -1, -1));

        jButtonVoltar.setText("Voltar");
        jButtonVoltar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonVoltarMouseClicked(evt);
            }
        });
        getContentPane().add(jButtonVoltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 360, -1, -1));

        jFTIsbn.setToolTipText("");
        getContentPane().add(jFTIsbn, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, 270, -1));
        getContentPane().add(inputInitTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, 270, -1));
        getContentPane().add(inputEndTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 200, 270, -1));

        jCheckBox1.setText("Turno Repetido");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, -1, -1));

        weekDayInput.setToolTipText("");
        weekDayInput.setEnabled(false);
        getContentPane().add(weekDayInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 270, 70, -1));

        labelWeek.setText("Dia da semana:");
        labelWeek.setEnabled(false);
        getContentPane().add(labelWeek, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 270, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonInserirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonInserirMouseClicked
        // TODO add your handling code here:
        String isbn = jFTIsbn.getText();
        String titulo = inputInitTime.getText();
        String autor = inputEndTime.getText();

        // TODO add function
        boolean checkFields = checkEmptyFields(new ArrayList<String>(){{
            add(isbn);
            add(titulo);
            add(autor);
        }});

        if (!checkFields) {
            JOptionPane.showMessageDialog(null, "Todos os campos têm de ser preenchidos!");
            return;
        }

        PreparedStatement statment = null;
        Connection con = null;
        try {
            //TODO change database and query
            con = DriverManager.getConnection("jdbc:mysql://localhost/bd_bliblioteca", "root", "");
            String sql = "INSERT INTO livro(isbn, titulo, autor, n_paginas, editora, tamanho)" +
            "VALUES(?, ?, ?, ?)";
            statment = con.prepareStatement(sql);
            statment.setString(1, isbn);
            statment.setString(2, titulo);
            statment.setString(3, autor);
            int rowsAffected = statment.executeUpdate();

            if (rowsAffected <= 0) {
                JOptionPane.showMessageDialog(null, "Falha ao inserir o registo.");
                return;
            }
            JOptionPane.showMessageDialog(null, "Registo inserido com sucesso!");

        } catch (SQLException e) {
            Logger.getLogger(FTurnsInsert.class.getName()).log(Level.SEVERE, null, e);
            JOptionPane.showMessageDialog(null, "Ligação à base de dados sem sucesso!");
        } catch (NumberFormatException e) {
            Logger.getLogger(FTurnsInsert.class.getName()).log(Level.SEVERE, null, e);
            JOptionPane.showMessageDialog(null, "O campo \"Nº de páginas\" tem de ter um valor numérico!");
        } finally {
            try {
                if (statment != null) statment.close();
                if (con != null) con.close();
            } catch (SQLException e) {
                Logger.getLogger(FTurnsInsert.class.getName()).log(Level.SEVERE, null, e);
            }

        }
        jFTIsbn.setText("");
        inputInitTime.setText("");
        inputEndTime.setText("");
    }//GEN-LAST:event_jButtonInserirMouseClicked

    private void jButtonInserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInserirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonInserirActionPerformed

    private void jButtonVoltarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonVoltarMouseClicked
        // TODO add your handling code here:
        FTurnsInit fpr = new FTurnsInit();
        fpr.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonVoltarMouseClicked

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private boolean checkEmptyFields(ArrayList<String> fields) {
        for (String textField : fields) {
            if (textField.isEmpty()) return false;
        }
        return true;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FTurnsInsert.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FTurnsInsert.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FTurnsInsert.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FTurnsInsert.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FTurnsInsert().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField inputEndTime;
    private javax.swing.JTextField inputInitTime;
    private javax.swing.JButton jButtonInserir;
    private javax.swing.JButton jButtonVoltar;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JTextField jFTIsbn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel labelWeek;
    private javax.swing.JTextField weekDayInput;
    // End of variables declaration//GEN-END:variables
}
