/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package turnsform;

import java.util.logging.Level;
import java.util.logging.Logger;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author ART
 */
public class FTurnsInsert extends javax.swing.JFrame {

    private String name;
    private String id;
    
    /**
     * Creates new form FTurnsInsert
     */
    public FTurnsInsert() {
        initComponents();
    }
    
    public FTurnsInsert(String name, String id) {
        this.name = name;
        this.id = id;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        labelDate = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnInsert = new javax.swing.JButton();
        btnReturn = new javax.swing.JButton();
        inputDate = new javax.swing.JTextField();
        inputStartTime = new javax.swing.JTextField();
        inputEndTime = new javax.swing.JTextField();
        checkRepeat = new javax.swing.JCheckBox();
        weekDayInput = new javax.swing.JTextField();
        labelDay = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setText("Inserir Turnos");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, -1, -1));

        labelDate.setText("Data:");
        getContentPane().add(labelDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, -1, -1));

        jLabel3.setText("Hora Inicio:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, -1, -1));

        jLabel4.setText("Hora Fim:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, -1, -1));

        btnInsert.setText("Inserir");
        btnInsert.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnInsertMouseClicked(evt);
            }
        });
        getContentPane().add(btnInsert, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 360, -1, -1));

        btnReturn.setText("Voltar");
        btnReturn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnReturnMouseClicked(evt);
            }
        });
        getContentPane().add(btnReturn, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 360, -1, -1));

        inputDate.setToolTipText("");
        getContentPane().add(inputDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, 270, -1));
        getContentPane().add(inputStartTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, 270, -1));
        getContentPane().add(inputEndTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 200, 270, -1));

        checkRepeat.setText("Turno Repetido");
        checkRepeat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                checkRepeatMouseClicked(evt);
            }
        });
        getContentPane().add(checkRepeat, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, -1, -1));

        weekDayInput.setToolTipText("");
        weekDayInput.setEnabled(false);
        getContentPane().add(weekDayInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 270, 70, -1));

        labelDay.setText("Dia da semana:");
        labelDay.setEnabled(false);
        getContentPane().add(labelDay, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 270, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnInsertMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInsertMouseClicked
        // TODO add your handling code here:
        String isbn = inputDate.getText();
        String titulo = inputStartTime.getText();
        String autor = inputEndTime.getText();

        // TODO add function
        boolean checkFields = checkEmptyFields(new ArrayList<String>(){{
            add(isbn);
            add(titulo);
            add(autor);
        }});

        if (!checkFields) {
            JOptionPane.showMessageDialog(null, "Todos os campos têm de ser preenchidos!");
            return;
        }

        PreparedStatement statment = null;
        Connection con = null;
        try {
            //TODO change database and query
            con = DriverManager.getConnection("jdbc:mysql://localhost/bd_bliblioteca", "root", "");
            String sql = "INSERT INTO livro(isbn, titulo, autor, n_paginas, editora, tamanho)" +
            "VALUES(?, ?, ?, ?)";
            statment = con.prepareStatement(sql);
            statment.setString(1, isbn);
            statment.setString(2, titulo);
            statment.setString(3, autor);
            int rowsAffected = statment.executeUpdate();

            if (rowsAffected <= 0) {
                JOptionPane.showMessageDialog(null, "Falha ao inserir o registo.");
                return;
            }
            JOptionPane.showMessageDialog(null, "Registo inserido com sucesso!");

        } catch (SQLException e) {
            Logger.getLogger(FTurnsInsert.class.getName()).log(Level.SEVERE, null, e);
            JOptionPane.showMessageDialog(null, "Ligação à base de dados sem sucesso!");
        } catch (NumberFormatException e) {
            Logger.getLogger(FTurnsInsert.class.getName()).log(Level.SEVERE, null, e);
            JOptionPane.showMessageDialog(null, "O campo \"Nº de páginas\" tem de ter um valor numérico!");
        } finally {
            try {
                if (statment != null) statment.close();
                if (con != null) con.close();
            } catch (SQLException e) {
                Logger.getLogger(FTurnsInsert.class.getName()).log(Level.SEVERE, null, e);
            }

        }
        inputDate.setText("");
        inputStartTime.setText("");
        inputEndTime.setText("");
    }//GEN-LAST:event_btnInsertMouseClicked

    private void btnReturnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReturnMouseClicked
        FTurnsInit fpr = new FTurnsInit();
        fpr.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnReturnMouseClicked

    private void checkRepeatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_checkRepeatMouseClicked
        if (checkRepeat.isSelected()) {
            labelDay.setEnabled(true);
            weekDayInput.setEnabled(true);
            labelDate.setEnabled(false);
            inputDate.setEnabled(false);
            inputDate.setText("");
        }
        else {
            labelDay.setEnabled(false);
            weekDayInput.setEnabled(false);
            weekDayInput.setText("");
            labelDate.setEnabled(true);
            inputDate.setEnabled(true);
        }
        
    }//GEN-LAST:event_checkRepeatMouseClicked

    private boolean checkEmptyFields(ArrayList<String> fields) {
        for (String textField : fields) {
            if (textField.isEmpty()) return false;
        }
        return true;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FTurnsInsert.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FTurnsInsert.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FTurnsInsert.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FTurnsInsert.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FTurnsInsert().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnInsert;
    private javax.swing.JButton btnReturn;
    private javax.swing.JCheckBox checkRepeat;
    private javax.swing.JTextField inputDate;
    private javax.swing.JTextField inputEndTime;
    private javax.swing.JTextField inputStartTime;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel labelDate;
    private javax.swing.JLabel labelDay;
    private javax.swing.JTextField weekDayInput;
    // End of variables declaration//GEN-END:variables
}
